// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         int64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id,string"`
	Username   string    `gorm:"column:username;type:varchar(32)" json:"username"`
	Age        int32     `gorm:"column:age;type:int unsigned;not null" json:"age"`
	Password   string    `gorm:"column:password;type:varchar(128)" json:"password"`
	CreateTime time.Time `gorm:"column:create_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"create_time"`
	UpdateTime time.Time `gorm:"column:update_time;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	Phone      string    `gorm:"column:phone;type:varchar(11);not null" json:"phone"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
